name: Pull request

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: Check code quality
        run: |
          poetry run ruff check src --output-format=github

      - name: Check code formatting
        run: |
          poetry run ruff format src --check
      - name: Test with pytest
        run: |
          poetry run pytest tests/unit
